const data = {
  products: [
    {
      name: 'Ghana: The Autobiography of Kwame Nkrumah',
      slug: 'ghana-the-autobiography-of-kwame-nkrumah',
      category: 'Shirts',
      image: '/images/Nkrumah1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Ghana: The Autobiography of Kwame Nkrumah',
      slug: 'ghana-the-autobiography-of-kwame-nkrumah',
      category: 'Shirts',
      image: '/images/Nkrumah1.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Ghana: The Autobiography of Kwame Nkrumah',
      slug: 'ghana-the-autobiography-of-kwame-nkrumah',
      category: 'Pants',
      image: '/images/Nkrumah1.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Ghana: The Autobiography of Kwame Nkrumah',
      slug: 'ghana-the-autobiography-of-kwame-nkrumah',
      category: 'Pants',
      image: '/images/Nkrumah1.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
